apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-app
  namespace: task-management
  labels:
    app: task-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-app
  template:
    metadata:
      labels:
        app: task-management-app
    spec:
      serviceAccountName: task-management-sa
      containers:
      - name: task-management-app
        image: task-management-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-service:27017/task_management?authSource=admin"
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /tasks/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /tasks/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-management-service
  namespace: task-management
spec:
  selector:
    app: task-management-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
