apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-management-sa
  namespace: task-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: task-management
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: task-management
subjects:
- kind: ServiceAccount
  name: task-management-sa
  namespace: task-management
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io
